services:
- type: web
  name: rabbitmq
  env: docker
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    generateValue: true
  - key: guest
    value: rabbitmq
  - key: guest
    generateValue: true
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq
    sizeGB: 10